# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 设置JDK环境
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

#      - name: 构建Maven
#        run: mvn -B package --file pom.xml
#
#      - name: 发布到Github packages
#        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#        env:
#          GITHUB_TOKEN: ${{ github.token }}

      - name: 部署搭配服务器
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            export PATH=/usr/local/bin:$PATH
            source /etc/profile
            java -version
            mvn -v
            cd /data/webapp/mall/mall-api
            git pull
            mvn clean install
            curl -X POST 127.0.0.1:8089/sactuator/shutdown
            nohup java -jar ./target/mall-0.0.1-SNAPSHOT.jar > console.log 2>&1 &
